name: CI - Build and Push Image (GHCR)

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
           ghcr.io/${{ github.repository_owner }}/devops-app:latest
           ghcr.io/${{ github.repository_owner }}/devops-app:${{ github.sha }}

                 - name: Update k8s manifest with image tag (commit SHA)
        run: |
          sed -i "s#ghcr.io/${{ github.repository_owner }}/devops-app:.*#ghcr.io/${{ github.repository_owner }}/devops-app:${{ github.sha }}#g" k8s/deployment.yaml
          git status
          git diff

      - name: Commit and push manifest update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/deployment.yaml
          git commit -m "chore: deploy ${{ github.sha }}" || exit 0
          git push